### ISSUE TITLE
Footer Link to GitHub Proifile Broken

### ISSUE THREAD

**Issue by sshaw** [piotrmurach/tty.github.io#2]
Links to https://github.com/peter-murach/

You may also want to check [the homepage link for tty-screen](https://rubygems.org/gems/tty-screen). It links to http://peter-murach.github.io/tty/.

**Comment by piotrmurach** [comment]
Thanks for spotting these. I've recently changed my 'identity' and it proved be tons of work.

**Comment by piotrmurach** [comment]
I have redesigned the site and changed all the links.

**Comment by piotrmurach** [comment]
If you fancy you can check it out @ [https://piotrmurach.github.io/tty/](https://piotrmurach.github.io/tty/). I believe it does a better job at explaining what tty libraries are for and let's you browser stuff more easily. I would be curious to have your thoughts?

**Comment by sshaw** [comment]
Site is nice, works well. So much so the only bit of semi-useful feed back I can offer is this: 

On desktop, when clicking on the API menu, I would be nice if clicking anywhere outside the menu would close it. Currently one has to click on API again :neckbeard:.

**Comment by sshaw** [comment]
Oh, found one thing: the rubygems homepage for tty-screen still points to http://peter-murach.github.io/tty/
